
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/cephyr/users/schmidte/Alvis/Paric_nolavis/ProbVLM/src/train_ProbVLM_CLIP-ViTB32.py", line 19, in <module>
    from utils import *
  File "/cephyr/users/schmidte/Alvis/Paric_nolavis/ProbVLM/src/utils.py", line 8, in <module>
    import torch
  File "/opt/conda/lib/python3.10/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/opt/conda/lib/python3.10/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/opt/conda/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /opt/conda/conda-bld/pytorch_1708025847130/work/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Traceback (most recent call last):
  File "/cephyr/users/schmidte/Alvis/Paric_nolavis/ProbVLM/src/train_ProbVLM_CLIP-ViTB32.py", line 19, in <module>
    from utils import *
  File "/cephyr/users/schmidte/Alvis/Paric_nolavis/ProbVLM/src/utils.py", line 13, in <module>
    import ds 
  File "/cephyr/users/schmidte/Alvis/Paric_nolavis/ProbVLM/src/ds/__init__.py", line 12, in <module>
    from ds._dataloader_extra import prepare_foodmeat_dataloaders, prepare_foodredmeat_dataloaders
  File "/cephyr/users/schmidte/Alvis/Paric_nolavis/ProbVLM/src/ds/_dataloader_extra.py", line 9, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'
